# Create with alias zdc='CURRENT_UID=$(id -u):$(id -g) docker-compose -p zones -f ~/eto-zone-maps/zones.yml'
version: '3'

services:
  db:
#    image: eto-zones-maps:latest
    build: ./docker/db
    restart: always
    env_file:
      - zones.yml.env
    volumes:
      - db:/var/lib/postgresql/data
      - ./initdb.d/:/Fc
    ports:
      - 5432:5432

volumes:
  db:
    driver: local
